house_pricing:
  train_dataset: D:\projects\spbu-ai-fundamentals\data\house_prices\train.csv
  test_dataset: D:\projects\spbu-ai-fundamentals\data\house_prices\test.csv
classification:
  wdbc: D:\projects\spbu-ai-fundamentals\data\classification/data.csv
  mushrooms: D:\projects\spbu-ai-fundamentals\data\classification/mushrooms.csv
clustering:
  flowcytometry: D:\projects\spbu-ai-fundamentals\data\flow_cytometry
